import { useState, useEffect, useRef, ImgHTMLAttributes, memo } from "react";
import { cn } from "@/lib/utils";

interface OptimizedImageProps extends ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
  priority?: boolean; // For above-fold images
  placeholder?: "blur" | "empty" | "skeleton";
  wrapperClassName?: string;
  aspectRatio?: string; // e.g., "16/9", "4/3", "1/1"
  quality?: number; // Image quality hint (not used directly, for future CDN integration)
}

// Check if browser supports WebP (cached result)
let webpSupport: boolean | null = null;
const supportsWebP = (): boolean => {
  if (webpSupport !== null) return webpSupport;
  if (typeof document === 'undefined') return false;
  
  const canvas = document.createElement('canvas');
  canvas.width = 1;
  canvas.height = 1;
  webpSupport = canvas.toDataURL('image/webp').indexOf('data:image/webp') === 0;
  return webpSupport;
};

// Check if browser supports AVIF
let avifSupport: boolean | null = null;
const supportsAVIF = (): boolean => {
  if (avifSupport !== null) return avifSupport;
  if (typeof document === 'undefined') return false;
  
  // AVIF detection is async, but we'll do a sync check for now
  avifSupport = false;
  return avifSupport;
};

// Image format priorities for modern browsers
const getOptimizedSources = (src: string): { avif?: string; webp?: string; original: string } => {
  // If it's already a data URL or external URL, return as-is
  if (src.startsWith('data:') || src.startsWith('http')) {
    return { original: src };
  }
  
  // Check if it's an imported asset (with hash in URL from Vite)
  const isViteAsset = src.includes('/assets/') && src.includes('-');
  
  // For local images, generate WebP paths
  // In production, these would be pre-generated by a build step
  const baseExt = src.match(/\.(jpg|jpeg|png|gif)$/i);
  
  if (!baseExt || isViteAsset) {
    return { original: src };
  }
  
  return {
    webp: src.replace(/\.(jpg|jpeg|png|gif)$/i, '.webp'),
    original: src
  };
};

// Preload critical images for LCP optimization
export const preloadImage = (src: string, priority: 'high' | 'low' = 'high') => {
  if (typeof document === 'undefined') return;
  
  const existingLink = document.querySelector(`link[href="${src}"]`);
  if (existingLink) return;
  
  const link = document.createElement('link');
  link.rel = 'preload';
  link.as = 'image';
  link.href = src;
  if (priority === 'high') {
    link.setAttribute('fetchpriority', 'high');
  }
  document.head.appendChild(link);
};

const OptimizedImage = memo(({
  src,
  alt,
  priority = false,
  placeholder = "skeleton",
  className,
  wrapperClassName,
  aspectRatio,
  quality,
  ...props
}: OptimizedImageProps) => {
  const [isLoaded, setIsLoaded] = useState(false);
  const [isInView, setIsInView] = useState(priority);
  const [hasError, setHasError] = useState(false);
  const imgRef = useRef<HTMLDivElement>(null);
  const observerRef = useRef<IntersectionObserver | null>(null);

  // Preload priority images immediately
  useEffect(() => {
    if (priority && src) {
      preloadImage(src, 'high');
    }
  }, [priority, src]);

  useEffect(() => {
    if (priority) {
      setIsInView(true);
      return;
    }

    observerRef.current = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsInView(true);
          observerRef.current?.disconnect();
        }
      },
      {
        rootMargin: "400px", // Start loading 400px before entering viewport for smoother UX
        threshold: 0,
      }
    );

    if (imgRef.current) {
      observerRef.current.observe(imgRef.current);
    }

    return () => observerRef.current?.disconnect();
  }, [priority]);

  const handleLoad = () => {
    setIsLoaded(true);
  };

  const handleError = () => {
    setHasError(true);
    setIsLoaded(true); // Still mark as loaded to remove skeleton
  };

  const sources = getOptimizedSources(src);
  const hasWebP = supportsWebP();
  const hasAVIF = supportsAVIF();

  return (
    <div 
      ref={imgRef}
      className={cn(
        "relative overflow-hidden",
        wrapperClassName
      )}
      style={aspectRatio ? { aspectRatio } : undefined}
    >
      {/* Skeleton/blur placeholder - prevents CLS */}
      {!isLoaded && (
        <div 
          className={cn(
            "absolute inset-0 will-change-opacity",
            placeholder === "skeleton" && "bg-muted animate-pulse",
            placeholder === "blur" && "bg-gradient-to-br from-muted/60 to-muted/40 backdrop-blur-sm"
          )}
          aria-hidden="true"
        />
      )}
      
      {isInView && !hasError && (
        <picture>
          {/* AVIF source for browsers that support it (best compression) */}
          {sources.avif && hasAVIF && (
            <source srcSet={sources.avif} type="image/avif" />
          )}
          {/* WebP source for browsers that support it */}
          {sources.webp && hasWebP && (
            <source srcSet={sources.webp} type="image/webp" />
          )}
          {/* Original image as fallback */}
          <img
            src={sources.original}
            alt={alt}
            loading={priority ? "eager" : "lazy"}
            decoding={priority ? "sync" : "async"}
            fetchPriority={priority ? "high" : "auto"}
            onLoad={handleLoad}
            onError={handleError}
            className={cn(
              "transition-opacity duration-300 will-change-opacity",
              isLoaded ? "opacity-100" : "opacity-0",
              className
            )}
            {...props}
          />
        </picture>
      )}

      {/* Error fallback */}
      {hasError && (
        <div className="absolute inset-0 flex items-center justify-center bg-muted/50">
          <span className="text-muted-foreground text-sm">Image unavailable</span>
        </div>
      )}
    </div>
  );
});

OptimizedImage.displayName = "OptimizedImage";

export default OptimizedImage;


